server:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
management:
  health:
    defaults:
      enabled: false

camel:
  health:
    enabled: false
    indicator:
      enabled: true
